In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, recall_score, f1_score, precision_score, confusion_matrix, classification_report

In [2]:
df = pd.read_csv("sprint1.csv")

In [3]:
df

,Unnamed: 0,est_diameter_min,est_diameter_max,relative_velocity,miss_distance,absolute_magnitude,hazardous
0,0,0.329622,0.737056,13569.249224,5.483974e+07,16.73,0
1,1,0.265800,0.594347,73588.726663,6.143813e+07,20.00,1
2,2,0.329622,0.737056,114258.692129,4.979872e+07,17.83,0
3,3,0.096506,0.215794,24764.303138,2.543497e+07,22.20,0
4,4,0.255009,0.570217,42737.733765,4.627557e+07,20.09,1
...,...,...,...,...,...,...,...
90824,90831,0.026580,0.059435,52078.886692,1.230039e+07,25.00,0
90825,90832,0.016771,0.037501,46114.605073,5.432121e+07,26.00,0
90826,90833,0.031956,0.071456,7566.807732,2.840077e+07,24.60,0
90827,90834,0.007321,0.016370,69199.154484,6.869206e+07,27.80,0
90828,90835,0.039862,0.089133,27024.455553,5.977213e+07,24.12,0

In [4]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [5]:
df.head()

,est_diameter_min,est_diameter_max,relative_velocity,miss_distance,absolute_magnitude,hazardous
0,0.329622,0.737056,13569.249224,5.483974e+07,16.73,0
1,0.265800,0.594347,73588.726663,6.143813e+07,20.00,1
2,0.329622,0.737056,114258.692129,4.979872e+07,17.83,0
3,0.096506,0.215794,24764.303138,2.543497e+07,22.20,0
4,0.255009,0.570217,42737.733765,4.627557e+07,20.09,1

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 90829 entries, 0 to 90828
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   est_diameter_min    90829 non-null  float64
 1   est_diameter_max    90829 non-null  float64
 2   relative_velocity   90829 non-null  float64
 3   miss_distance       90829 non-null  float64
 4   absolute_magnitude  90829 non-null  float64
 5   hazardous           90829 non-null  int64
dtypes: float64(5), int64(1)
memory usage: 4.2 MB

In [7]:
df.describe()

,est_diameter_min,est_diameter_max,relative_velocity,miss_distance,absolute_magnitude,hazardous
count,90829.000000,90829.000000,90829.000000,9.082900e+04,90829.000000,90829.000000
mean,0.096518,0.215820,47810.462649,3.706500e+07,23.527844,0.097249
std,0.103482,0.231392,24464.223574,2.235196e+07,2.891665,0.296298
min,0.000609,0.001362,203.346433,6.745533e+03,14.800000,0.000000
25%,0.019256,0.043057,28617.551535,1.720845e+07,21.340000,0.000000
50%,0.048368,0.108153,44190.593061,3.784531e+07,23.700000,0.000000
75%,0.143402,0.320656,62924.825373,5.654683e+07,25.700000,0.000000
max,0.329622,0.737056,114385.736130,7.479865e+07,32.240000,1.000000

## Train & Test Data

In [8]:
x = df.drop("hazardous", axis=1)
y = df["hazardous"]

In [9]:
x.shape, y.shape

((90829, 5), (90829,))

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [11]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((72663, 5), (18166, 5), (72663,), (18166,))

## Feature Scaling

In [12]:
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)

In [13]:
x_train_scaled

array([[-0.74679691, -0.74679691,  0.08131269, -1.36658496,  0.75074771],
       [-0.80979067, -0.80979067, -0.03220487,  0.72186099,  1.06138337],
       [-0.04385342, -0.04385342,  0.17540828, -0.38786429, -0.42276478],
       ...,
       [ 0.29415524,  0.29415524,  0.29166312,  0.18307785, -0.6643703 ],
       [ 1.01158907,  1.01158907,  1.05543701, -0.74058868, -1.00952103],
       [ 0.47588145,  0.47588145,  0.96784764, -0.63804752, -0.76791552]],
      shape=(72663, 5))

In [43]:
x_test_scaled

array([[ 1.01158907,  1.01158907,  1.71232968,  0.25414408, -1.00952103],
       [-0.75515273, -0.75515273, -0.84505809,  1.54071378,  0.78526278],
       [ 0.47588145,  0.47588145, -0.77702137,  1.54233546, -0.76791552],
       ...,
       [ 1.87754198,  1.87754198, -1.14256882,  0.53852024, -1.28564161],
       [-0.59461582, -0.59461582,  0.94691296,  0.99118745,  0.30205175],
       [ 0.40016548,  0.40016548,  0.04119014, -0.00345107, -0.72649743]],
      shape=(18166, 5))

## Baseline Model (Logistic Regression)

In [14]:
baseline_model = LogisticRegression()

baseline_model.fit(x_train_scaled, Y_train)
baseline_pred = baseline_model.predict(x_test_scaled)

In [15]:
baseline_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(18166,))

In [54]:
baseline_acc = accuracy_score(Y_
                              test, baseline_pred)
print("Baseline Accuracy:", baseline_acc)

Baseline Accuracy: 0.8933722338434438

In [16]:
print(classification_report(Y_test, baseline_pred))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94     16399
           1       0.29      0.07      0.11      1767

    accuracy                           0.89     18166
   macro avg       0.60      0.52      0.52     18166
weighted avg       0.85      0.89      0.86     18166

In [17]:
confusion_matrix(Y_test, baseline_pred)

array([[16114,   285],
       [ 1652,   115]])

## Training Multiple Models

In [18]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree":DecisionTreeClassifier(random_state=42),
    "Random Forest":RandomForestClassifier(random_state=42),
    "SVM":SVC(),
    "Naive Bayes":GaussianNB()
}

In [19]:
models

{'Logistic Regression': LogisticRegression(max_iter=1000),
 'Decision Tree': DecisionTreeClassifier(random_state=42),
 'Random Forest': RandomForestClassifier(random_state=42),
 'SVM': SVC(),
 'Naive Bayes': GaussianNB()}

In [20]:
results = []

In [21]:
for name, model in models.items():

    print("\n" + "="*50)
    print("model :", name)

    if name in ["Logistic Regression", "SVM"]:
        model.fit(x_train_scaled, Y_train)
        train_pred = model.predict(x_train_scaled)
        test_pred = model.predict(x_test_scaled)

    else:
        model.fit(X_train, Y_train)
        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        train_accuracy = accuracy_score(train_pred, Y_train)
        test_accuracy = accuracy_score(test_pred, Y_test)

        precision = precision_score(test_pred, Y_test)
        recall = recall_score(test_pred, Y_test)
        f1 = f1_score(test_pred, Y_test)

        print("Train Accuracy:", round(train_accuracy,4))
        print("Test Accuracy :", round(test_accuracy,4))
        print("Precision     :", round(precision,4))
        print("Recall        :", round(recall,4))
        print("F1 Score      :", round(f1,4))

        print("\nConfision Matrix")
        print(confusion_matrix(test_pred, Y_test))

        results.append([
            name,
            train_accuracy,
            test_accuracy,
            precision,
            recall,
            f1
        ])

==================================================
model : Logistic Regression

==================================================
model : Decision Tree
Train Accuracy: 1.0
Test Accuracy : 0.8938
Precision     : 0.4663
Recall        : 0.455
F1 Score      : 0.4606

Confision Matrix
[[15412   943]
 [  987   824]]

==================================================
model : Random Forest
Train Accuracy: 1.0
Test Accuracy : 0.9151
Precision     : 0.3848
Recall        : 0.5991
F1 Score      : 0.4686

Confision Matrix
[[15944  1087]
 [  455   680]]

==================================================
model : SVM

==================================================
model : Naive Bayes
Train Accuracy: 0.9028
Test Accuracy : 0.9027
Precision     : 0.0
Recall        : 0.0
F1 Score      : 0.0

Confision Matrix
[[16399  1767]
 [    0     0]]

C:\Users\SAMI\anaconda3\envs\ml_env\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [25]:
results

[['Decision Tree',
  1.0,
  0.8937575690851041,
  0.4663271080928127,
  0.45499723909442297,
  0.4605925097820011],
 ['Random Forest',
  1.0,
  0.9151161510514148,
  0.38483305036785515,
  0.5991189427312775,
  0.4686423156443832],
 ['Naive Bayes', 0.9027565611108818, 0.9027303754266212, 0.0, 0.0, 0.0]]

##  Model Comparison Table

In [26]:
comparison_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Train Accuracy",
        "Test Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)

In [27]:
comparison_df.head()

           Model  Train Accuracy  Test Accuracy  Precision    Recall  F1 Score
0  Decision Tree        1.000000       0.893758   0.466327  0.454997  0.460593
1  Random Forest        1.000000       0.915116   0.384833  0.599119  0.468642
2    Naive Bayes        0.902757       0.902730   0.000000  0.000000  0.000000

In [28]:
comparison_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Model           3 non-null      str
 1   Train Accuracy  3 non-null      float64
 2   Test Accuracy   3 non-null      float64
 3   Precision       3 non-null      float64
 4   Recall          3 non-null      float64
 5   F1 Score        3 non-null      float64
dtypes: float64(5), str(1)
memory usage: 276.0 bytes

In [29]:
comparison_df.sort_values(
    by="Test Accuracy",
    ascending=False
)

           Model  Train Accuracy  Test Accuracy  Precision    Recall  F1 Score
1  Random Forest        1.000000       0.915116   0.384833  0.599119  0.468642
2    Naive Bayes        0.902757       0.902730   0.000000  0.000000  0.000000
0  Decision Tree        1.000000       0.893758   0.466327  0.454997  0.460593

In [30]:
comparison_df

           Model  Train Accuracy  Test Accuracy  Precision    Recall  F1 Score
0  Decision Tree        1.000000       0.893758   0.466327  0.454997  0.460593
1  Random Forest        1.000000       0.915116   0.384833  0.599119  0.468642
2    Naive Bayes        0.902757       0.902730   0.000000  0.000000  0.000000

## Check Overfitting and Underfitting

- Train Accuracy >> Test Accuracy

In [31]:
comparison_df["Over Fitting"] = np.where(
    comparison_df["Train Accuracy"] - comparison_df["Test Accuracy"] > 0.05,
    "Yes",
    "No"
)

In [32]:
comparison_df.head()

,Model,Train Accuracy,Test Accuracy,Precision,Recall,F1 Score,Over Fitting
0,Decision Tree,1.000000,0.893758,0.466327,0.454997,0.460593,Yes
1,Random Forest,1.000000,0.915116,0.384833,0.599119,0.468642,Yes
2,Naive Bayes,0.902757,0.902730,0.000000,0.000000,0.000000,No

In [33]:
def remarks(row):
    if row["Over Fitting"] == "Yes":
        return "Model Overfits"

    elif row["Test Accuracy"] > 0.9:
        return "Excellent"

    elif row["Test Accuracy"] > 0.8:
        return "Good"

    else:
        return "Needs Improvement"

In [34]:
comparison_df["Remarks"] = comparison_df.apply(
    remarks,
    axis=1
)

In [35]:
comparison_df.head()

,Model,Train Accuracy,Test Accuracy,Precision,Recall,F1 Score,Over Fitting,Remarks
0,Decision Tree,1.000000,0.893758,0.466327,0.454997,0.460593,Yes,Model Overfits
1,Random Forest,1.000000,0.915116,0.384833,0.599119,0.468642,Yes,Model Overfits
2,Naive Bayes,0.902757,0.902730,0.000000,0.000000,0.000000,No,Excellent

## Best Performing Model

In [36]:
best_model = comparison_df.loc[
    comparison_df["Test Accuracy"].idxmax()
]

print(best_model)

Model              Random Forest
Train Accuracy               1.0
Test Accuracy           0.915116
Precision               0.384833
Recall                  0.599119
F1 Score                0.468642
Over Fitting                 Yes
Remarks           Model Overfits
Name: 1, dtype: object

## Sprint 2 Conclusion

- Five classification models were trained and evaluated using Accuracy, Precision, Recall, and F1 Score. Although SVM and Random Forest achieved similar accuracy, Random Forest produced the best balance between Precision and Recall and achieved the highest F1 Score (0.473). Therefore, Random Forest was selected as the best-performing model for hazardous asteroid classification.

## Final Choice:  Random Forest Classifier